
pool:
  vmImage: ubuntu-latest

steps:
- task: calculatorPassObj@0
  inputs:
    Number1: 1
    Number2: 2
    Operation: '+'
  name: "calctask1"
  
  
- task: PowerShell@2
  name: "getResult"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "$(calctask1.outputVar)" 
      
- task: PowerShell@2
  name: "output"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "$(getResult.result)" 


