
pool:
  vmImage: ubuntu-latest

steps:
- task: calculatorPassObj@0
  inputs:
    Number1: 1
    Number2: 2
    Operation: '+'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "$(outputVar)""