
pool:
  vmImage: ubuntu-latest

steps:
- task: calculatorPassObj@0
  inputs:
    Number1: 1
    Number2: 2
    Operation: '+'
  name: "calctask"
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "$(calctask.outputVar)"