
pool:
  vmImage: ubuntu-latest

steps:
- task: calculatorPassObj@0
  inputs:
    Number1: 1
    Number2: 2
    Operation: '+'
  env:
    name: "calctask"
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "1+2"